# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15-P71Yqq4WiKS0ZEvUN8qcALwKoufLfv
"""

#1
a = ["mobil", "1500", "merah", "4"]
print(a)

a.append("214.200.000")
print(a)
a.append("SUV")
print(a)
a.insert(1,"toyota rocky")
print(a)

#2
ket = """ selamat datang di aplikasi menghitung bangun datar masukkan pilihan :
1. menghitung luas persegi
2. menghitung luas lingkaran
3. menghitung luas segitiga"""

pilihan=input(ket)

match pilihan:
    case "1":
        print ("kamu memilih 1 untuk menghitung luas persegi")
        sisi = int(input ("masukan sisi ?"))
        luasP = sisi*sisi
        print ("luas persegi yang sisinya ", sisi, "adalah " ,luasP)
    case "2":
        print ("kamu memilih 2 untuk menghitung luas lingkaran")
        jari2 = float(input ("masukan jarijari jari2?"))
        luasL = 3.14*jari2*jari2
        print ("luas lingkaran yang jari2nya ", jari2, "adalah ",int(luasL))
    case "3":
        print ("kamu memilih 3 untuk menghitung luas segitiga")
        alas = int(input ("masukan alas ?"))
        tinggi = int(input ("masukan tinggi ?"))
        luasS = 1/2*alas*tinggi
        print ("luas segitiga yang alasnya ", alas, "dan tingginya ", tinggi, "adalah", int(luasS))
    case _:
        print("anda salah memilih pilihan")